# : Manager [[[

[mgr]
cwd = { fg = "#f1dfdb" }

# Tab
tab_active = { fg = "#561f12", bg = "#ffb4a3", bold = true }
tab_inactive = { fg = "#ffdad2", bg = "#3a0a02" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#f1c147", bg = "#f1c147" }
marker_cut = { fg = "#f8e1a6", bg = "#f8e1a6" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dbc58c", bg = "#dbc58c" }

# Count
count_copied = { fg = "#241a00", bg = "#f8e1a6" }
count_cut = { fg = "#241a00", bg = "#f8e1a6" }
count_selected = { fg = "#561f12", bg = "#dbc58c" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb4a3" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#561f12", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb4a3", fg = "#561f12", bold = true }
normal_alt  = { bg = "#534340", fg = "#d8c2bd" }

# Select mode
select_main = { bg = "#e7bdb4", fg = "#442a24", bold = true }
select_alt  = { bg = "#534340", fg = "#d8c2bd" }

# Unset mode
unset_main = { bg = "#dbc58c", fg = "#3c2f04", bold = true }
unset_alt  = { bg = "#534340", fg = "#d8c2bd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb4a3", bg = "#423734" }
progress_error = { fg = "#ffb4ab", bg = "#423734" }

# Permissions
permissions_t = { fg = "#c25740" }
permissions_w = { fg = "#9d7f31" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#edb118" }
permissions_s = { fg = "#ff5c39" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb4a3" }
active = { fg = "#dbc58c", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb4a3" }
value = { fg = "#f1dfdb" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb4a3", bold = true, bg = "#1a110f" }
inactive = { fg = "#e7bdb4", bg = "#1a110f" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb4a3", bg = "#561f12" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb4a3" }
title = {}
hovered = { fg = "#f8e1a6", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423734" }
cand = { fg = "#ffb4a3" }
rest = { fg = "#561f12" }
desc = { fg = "#f1dfdb" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f1dfdb" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f1dfdb" }
run = { fg = "#f1dfdb" }
footer = { fg = "#442a24", bg = "#e7bdb4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#dbc58c" }
title_warn = { fg = "#ffb4a3" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f1dfdb" },
    { name = "*/", fg = "#ffb4a3" },
]

# : ]]]